### ISSUE TITLE
[Feature Request]: Add support for Vladmantics fork of Automatics webui

### ISSUE THREAD

**Issue by hassan-sd** [kabachuha/sd-webui-text2video#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Allow sd-webui-text2video to be compatible with Vlads automatic repo which has many users.

### Proposed workflow

Same steps as it's accessed today in Automatics repo

### Additional information

According to Vladmantic, he said:

> No, it's because extension checks cmdflags which are different. Extension should check if xformers are enabled or not, not check cmdflags from core app ever.
> 
> I cannot support extensions that do things the wrong way and hard code things that prevent any kind of change ever.

https://github.com/vladmandic/automatic/issues/1490

When we try to use this extension in Vlads fork we face this error

Exception occurred: 'Namespace' object has no attribute 'force_enable_xformers'

**Comment by lebakerino** [comment]
Interesting, I was actually trying to use txt2video earlier after seeing the new models for it and ran into an error, looking like the one at the bottom of your post, I was going to ask on here but it seems it may be the same issue. Hope it gets fixed.

**Comment by drax-xard** [comment]
I second the request, I'd love to use this extension in SD.Next.

**Comment by ShmuelRonen** [comment]
I discussed this with the Vladomatic-Automatic developer and he wrote me the following:

it's because extension checks cmdflags which are different. Extension should check if xformers are enabled or not, not check cmdflags from core app ever.

I cannot support extensions that do things the wrong way and hard code things that prevent any kind of change ever.

What fails is extension check of core repo command line flags - which it should never do. And that fails because flags are clearly different.

**Comment by kabachuha** [comment]
Thanks for noting! Maybe there will be some workaround here
